name: Windows Vulkan SDK Test

on:
  workflow_dispatch:
    inputs:
      test_vulkan_only:
        description: 'Test only Vulkan SDK installation'
        required: false
        default: 'true'

jobs:
  # ============================================================================
  # Simple test to verify Vulkan SDK installation works
  # ============================================================================
  test-vulkan-install:
    name: Test Vulkan SDK Installation
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      
      - name: Test different Vulkan SDK installation methods
        run: |
          Write-Host "🔧 Testing Vulkan SDK installation methods..."
          
          # Method 1: Try latest available version
          Write-Host "Method 1: Installing latest Vulkan SDK..."
          choco install vulkan-sdk -y
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Method 1 SUCCESS: Latest Vulkan SDK installed"
            $vulkan_ver = choco list vulkan-sdk --local-only
            Write-Host "Installed version: $vulkan_ver"
          } else {
            Write-Host "❌ Method 1 FAILED: Latest Vulkan SDK installation failed"
          }
          
          # Method 2: Try specific recent version
          Write-Host "Method 2: Trying specific version 1.3.268.0..."
          choco install vulkan-sdk --version=1.3.268.0 -y
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Method 2 SUCCESS: Vulkan SDK 1.3.268.0 installed"
          } else {
            Write-Host "❌ Method 2 FAILED: Version 1.3.268.0 not available"
          }
          
          # Method 3: Try another specific version
          Write-Host "Method 3: Trying specific version 1.3.250.0..."
          choco install vulkan-sdk --version=1.3.250.0 -y
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Method 3 SUCCESS: Vulkan SDK 1.3.250.0 installed"
          } else {
            Write-Host "❌ Method 3 FAILED: Version 1.3.250.0 not available"
          }
          
          # Check what versions are available
          Write-Host "Available Vulkan SDK versions:"
          choco list vulkan-sdk --all-versions
          
          # Verify installation
          Write-Host "Checking if Vulkan SDK is properly installed:"
          if (Test-Path "C:\VulkanSDK") {
            Write-Host "✅ Vulkan SDK directory found"
            Get-ChildItem "C:\VulkanSDK" | Select-Object Name
          } else {
            Write-Host "❌ Vulkan SDK directory not found"
          }
          
          # Check environment variables
          Write-Host "Vulkan environment variables:"
          $env:VULKAN_SDK
          $env:VK_SDK_PATH
      
      - name: Test Vulkan tools
        run: |
          Write-Host "Testing Vulkan tools availability..."
          if (Get-Command vulkaninfo -ErrorAction SilentlyContinue) {
            Write-Host "✅ vulkaninfo command found"
            vulkaninfo --version
          } else {
            Write-Host "❌ vulkaninfo command not found"
          }
          
          if (Get-Command glslc -ErrorAction SilentlyContinue) {
            Write-Host "✅ glslc command found"
            glslc --version
          } else {
            Write-Host "❌ glslc command not found"
          }
      
      - name: Summary
        run: |
          Write-Host "🎯 Vulkan SDK Installation Test Summary:"
          Write-Host "This test workflow can be deleted after successful Vulkan SDK installation is confirmed."
          Write-Host "Next step: Update the main Windows workflow with the working Vulkan SDK version."
